### ISSUE TITLE
关于页面如何实现？

### ISSUE THREAD

**Issue by hilaliu** [halo-sigs/halo-theme-obsidian#2]
原主题：分为三部分（自我介绍、开源项目、设备）
<img width="969" alt="image" src="https://github.com/halo-sigs/halo-theme-obsidian/assets/110895612/655fccdf-c1bf-44ff-bada-5435fb925c17">
<img width="855" alt="image" src="https://github.com/halo-sigs/halo-theme-obsidian/assets/110895612/9ec313ef-4bdc-4b96-9535-5c37422e0929">
我们的主题是提供一个模版页面供用户自己填写样式还是开一个单独的设置，只让用户填入这三个（自我介绍、开源项目、设备）的值

**Comment by ruibaby** [comment]
直接使用 page.html 即可。
