### ISSUE TITLE
真好看，大佬有没有微信群

### ISSUE THREAD

**Issue by AtomWorld** [halo-sigs/halo-theme-obsidian#4]
1

**Comment by ruibaby** [comment]
我们目前没有公开的微信群，如果有问题反馈在 GitHub 即可。此外，其他公开的社区可查看：https://halo.run/#:~:text=%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE-,%E7%A4%BE%E5%8C%BA,-%E5%AE%98%E6%96%B9%E8%AE%BA%E5%9D%9B
